CFLAGS?=-Wall -DWITH_COAP=13
LDFLAGS?=-static
iotgrid:	iotgrid.o 
install:	iotgrid
#iotgridd:	iotgridd.o 
#install:	iotgridd
#	strip iotgridd
#	mkdir -p $(DESTDIR)/$(PREFIX)/bin
#	cp -p iotgridd $(DESTDIR)/$(PREFIX)/bin
clean:
	rm -f *.o iotgrid iotgridd
